[package]
name = "pnvm_bench"
version = "0.1.0"
authors = ["Xu <xuchen@u.nus.edu>"]

[dependencies]
pnvm_sys = { path = "../pnvm_sys"}
rand = "0.5"
log = {version = "0.4"}
env_logger = "0.4"

[features]
unstable = ["pnvm_sys/unstable"]
