THREAD_NUM = 16
CHUNK_SIZE = 512
FILE_SIZE = 100000
THD_BLOCK_SIZE = 1000000
OPS_NUM = 10000000
REPEAT_NUM = 5
PMDK_MODE = "simple"
DEST_MODE = "MmapNVM"
FLUSH_FREQ = 2000
BENCH_TYPE = "FlushFreq"
PRINT_HEADER = true

