[package]
name = "pnvm_lib"
version = "0.1.0"
authors = ["Ricky Chen Xu <xuchen@u.nus.edu>"]

[dependencies]
pnvm_sys = { path = "../pnvm_sys"}
log = {version = "0.4"}
env_logger = "0.4"
lazy_static = "1.0"
libc = "0.2"
crossbeam = "0.3.0"
